//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessKiller.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcessKiller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream alert {
            get {
                return ResourceManager.GetStream("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (12/12/2017) 的本地化字符串。
        /// </summary>
        internal static string Application_PublishDate {
            get {
                return ResourceManager.GetString("Application_PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://bbs.duowan.com/thread-45386278-1-1.html 的本地化字符串。
        /// </summary>
        internal static string Application_Web_HomePage {
            get {
                return ResourceManager.GetString("Application_Web_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小猪双开器 的本地化字符串。
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到龙之谷主程序路径[DragonNest.exe], 请在设置中手动添加主程序路径 的本地化字符串。
        /// </summary>
        internal static string DNExe_NotFound_Message {
            get {
                return ResourceManager.GetString("DNExe_NotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器未选择，请在设置中选择大区 的本地化字符串。
        /// </summary>
        internal static string DNServer_NotFound_Message {
            get {
                return ResourceManager.GetString("DNServer_NotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DragonNest 的本地化字符串。
        /// </summary>
        internal static string DragonNest_Exe_Name {
            get {
                return ResourceManager.GetString("DragonNest_Exe_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dnlauncher 的本地化字符串。
        /// </summary>
        internal static string DragonNest_LauncherExe_Name {
            get {
                return ResourceManager.GetString("DragonNest_LauncherExe_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOFTWARE\WOW6432Node\shandagames\DragonNest 的本地化字符串。
        /// </summary>
        internal static string DragonNest_Registry_Path {
            get {
                return ResourceManager.GetString("DragonNest_Registry_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] handle {
            get {
                object obj = ResourceManager.GetObject("handle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 正在断开连接中... 的本地化字符串。
        /// </summary>
        internal static string MainForm_button_click_KillingProcessMessage {
            get {
                return ResourceManager.GetString("MainForm_button_click_KillingProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本: 的本地化字符串。
        /// </summary>
        internal static string MainForm_GetNewVersionDownloadLinkLabel_NewVersionFound_Message {
            get {
                return ResourceManager.GetString("MainForm_GetNewVersionDownloadLinkLabel_NewVersionFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击前往下载页 的本地化字符串。
        /// </summary>
        internal static string MainForm_GetNewVersionDownloadLinkLabel_NewVersionFound_Message_End {
            get {
                return ResourceManager.GetString("MainForm_GetNewVersionDownloadLinkLabel_NewVersionFound_Message_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗口 的本地化字符串。
        /// </summary>
        internal static string MainForm_GetProcessButton_ProcessButtonHighlightedTitle {
            get {
                return ResourceManager.GetString("MainForm_GetProcessButton_ProcessButtonHighlightedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点我切换至该窗口 的本地化字符串。
        /// </summary>
        internal static string MainForm_GetProcessButton_ProcessButtonTitle {
            get {
                return ResourceManager.GetString("MainForm_GetProcessButton_ProcessButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string MainForm_GetSettingsButton_SettingsButtonTitle {
            get {
                return ResourceManager.GetString("MainForm_GetSettingsButton_SettingsButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏 的本地化字符串。
        /// </summary>
        internal static string MainForm_GetStartGameButton_title {
            get {
                return ResourceManager.GetString("MainForm_GetStartGameButton_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有问题或者有疑问先看帖子，还有问题的话加群来问吧，群号: 610614351 的本地化字符串。
        /// </summary>
        internal static string MainForm_HelpButton_Message {
            get {
                return ResourceManager.GetString("MainForm_HelpButton_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点我或按键断开连接 的本地化字符串。
        /// </summary>
        internal static string MainForm_InitializeButtons_ClickToKillProcessHighlightedMessage {
            get {
                return ResourceManager.GetString("MainForm_InitializeButtons_ClickToKillProcessHighlightedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点我断开连接 的本地化字符串。
        /// </summary>
        internal static string MainForm_InitializeButtons_ClickToKillProcessMessage {
            get {
                return ResourceManager.GetString("MainForm_InitializeButtons_ClickToKillProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 柒才  更新者 双私 的本地化字符串。
        /// </summary>
        internal static string MainForm_InitializeCopyRightLabel_CopyrightMessage {
            get {
                return ResourceManager.GetString("MainForm_InitializeCopyRightLabel_CopyrightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本: 的本地化字符串。
        /// </summary>
        internal static string MainForm_InitializeVersionLabel_Version {
            get {
                return ResourceManager.GetString("MainForm_InitializeVersionLabel_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果需要多开，请等游戏完全启动或登陆后再点击启动游戏按钮 的本地化字符串。
        /// </summary>
        internal static string MainForm_start_game_button_first_click_message {
            get {
                return ResourceManager.GetString("MainForm_start_game_button_first_click_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏启动中... 的本地化字符串。
        /// </summary>
        internal static string MainForm_start_game_button_game_start_message {
            get {
                return ResourceManager.GetString("MainForm_start_game_button_game_start_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 掉线时出现问题：  的本地化字符串。
        /// </summary>
        internal static string ProcessButton_DisconnectExistingTCPConnections_ErrorMessage {
            get {
                return ResourceManager.GetString("ProcessButton_DisconnectExistingTCPConnections_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请右键以管理员身份打开此程序 的本地化字符串。
        /// </summary>
        internal static string Program_ShowAdminErrorDialogBox_AdminPrivilegeMessage {
            get {
                return ResourceManager.GetString("Program_ShowAdminErrorDialogBox_AdminPrivilegeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 116.211.8.173;116.211.4.101 14301;14301 南方电信一区
        ///116.211.2.168;116.211.2.170 14301;14301 南方电信二区
        ///116.211.2.151;116.221.2.153 14301;14301 华东电信一区
        ///116.211.2.169;116.211.2.171 14301;14301 华东电信二区
        ///115.238.27.95;115.238.22.201 14301;14301 华东电信七区
        ///14.152.76.110;14.152.76.94 14301;14301 华南电信一区
        ///14.152.76.111;14.152.76.95 14301;14301 华南电信三区
        ///116.211.2.199;116.211.4.14 14301;14301 华中电信一区
        ///116.211.2.181;116.211.2.183 14301;14301 西南电信一区
        ///111.161.33.30;111.161.33.31 14301;14301 华北网通一区
        ///111.161.33.10;111.161.33.12 14301;14301 华北网通 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string servers {
            get {
                return ResourceManager.GetString("servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用秒掉功能会增加封号风险，请慎重使用，如果被反外挂发现，请立即停止使用 的本地化字符串。
        /// </summary>
        internal static string SettingsForm_DisableProcessKillCheckBox_CheckedChanged_Warnning {
            get {
                return ResourceManager.GetString("SettingsForm_DisableProcessKillCheckBox_CheckedChanged_Warnning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间设置必须大于0 的本地化字符串。
        /// </summary>
        internal static string SettingsForm_InvalidField_CountDownTime {
            get {
                return ResourceManager.GetString("SettingsForm_InvalidField_CountDownTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 想啥呢？提示时间必须小于倒计时时间 (mdzz) 的本地化字符串。
        /// </summary>
        internal static string SettingsForm_InvalidField_CountDownWarnningTime {
            get {
                return ResourceManager.GetString("SettingsForm_InvalidField_CountDownWarnningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器设置手动模式下必须设置大区和Ip和端口！ 的本地化字符串。
        /// </summary>
        internal static string SettingsForm_InvalidField_ipsetting {
            get {
                return ResourceManager.GetString("SettingsForm_InvalidField_ipsetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择龙之谷游戏文件夹(包含游戏启动程序的根目录) 的本地化字符串。
        /// </summary>
        internal static string SettingsForm_PathSelection_Description {
            get {
                return ResourceManager.GetString("SettingsForm_PathSelection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未在该目录下发现龙之谷启动程序，请选择含有龙之谷启动程序的游戏目录 的本地化字符串。
        /// </summary>
        internal static string SettingsForm_PathSelection_InvalidPath_Message {
            get {
                return ResourceManager.GetString("SettingsForm_PathSelection_InvalidPath_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers 的本地化字符串。
        /// </summary>
        internal static string WINNT_AppCompatFlags_Registry_Path {
            get {
                return ResourceManager.GetString("WINNT_AppCompatFlags_Registry_Path", resourceCulture);
            }
        }
    }
}
